### PR TITLE
Improved PDF performance by using SVGs instead of PNGs

### PR DESCRIPTION
**Pull request by realmayus**
#### Why️?

Currently, opening kanji sheets takes a long time due to the PNGs being used in the PDFs. I tested this on multiple platforms and I can confirm that this doesn't have anything to do with the internet speed because even when opening the files locally, they take a long time to display. Safari even had to reload a 10-page PDF twice on iOS in order for it to display correctly.

I was able to confirm this on these platforms/apps:
- macOS / Firefox
- macOS / Preview (pre-installed app from Apple)
- iOS / Safari
- iOS / GoodNotes

After modifying the template and the code to use SVGs this issue is fixed. The PDFs now open instantly (they took up to 20 seconds *per page* before).
This unfortunately slows down the PDF generation a bit.

#### What Changed?

- created function to adjust the font size and family
- created function to generate gray SVGs without the numbers for the smaller boxes the user uses for tracing the kanji
- changed the template to embed the SVGs

### CODE REVIEW

**Comment by realmayus** [comment]
I just saw that the sheets were generated with SVGs before. Maybe we can find a way to fix the background bug (where some lines seem to be off or missing) without using PNGs

**Comment by realmayus** [comment]
I fixed the background bug by using <div>s instead of the background image. PDFs are now opening blazing fast!

97f2d51

**Comment by realmayus** [comment]
Fixes #9

**Comment by aruke** [comment]
@realmayus Do you have a PDF file containing each SVG and PNG kanjis? I would like to try the difference on other machines too. 
Also, I think as long as the PDF is used for printing purpose only, the render speed should not matter (unless the printer read the file slow). What do you think?

**Comment by realmayus** [comment]
@aruke I think that some people want to fill in the kanji sheets on e.g. iPads (including myself). The loading time of the PNG version is so slow that even the preview app crashed on my iPad.
Here's a comparison:
[fast.pdf](https://github.com/aruke/kanji.sh/files/5830458/fast.pdf)
[slow.pdf](https://github.com/aruke/kanji.sh/files/5830460/slow.pdf)

**Comment by aruke** [comment]
I see, the file size also becomes larger with the PNGs, and I agree with you. (Just had to see it with my own eyes/stopwatch)
I have changed the kanji generation flow with this PR https://github.com/aruke/kanji.sh/pull/13
So, after merging https://github.com/aruke/kanji.sh/pull/13 into dev, I will create one more PR to revert the original SVG rendering, with some code from your PR. Would you like to review these?

**Comment by realmayus** [comment]
Sure! :D

**Pull request closed without merging**
